;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="StateTree",DevComment="")
+GameplayTagList=(Tag="StateTree.Action",DevComment="")
+GameplayTagList=(Tag="StateTree.Action.Attack",DevComment="")
+GameplayTagList=(Tag="StateTree.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion.Idle",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion.Movement",DevComment="")
+GameplayTagList=(Tag="StateTree.Status",DevComment="")

