;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="EnemyStateTree",NewTagName="EnemyStates")
+GameplayTagRedirects=(OldTagName="EnemyStateTree.Locomotion.Move.Standstill",NewTagName="EnemyStateTree.Locomotion.Move.Default")
+GameplayTagList=(Tag="EnemyStateTree.Action",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Action.Attack",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Action.Idle",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion.Idle",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion.Move",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion.Move.Approach",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion.Move.Default",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Locomotion.Move.Retreat",DevComment="")
+GameplayTagList=(Tag="EnemyStateTree.Status",DevComment="")
+GameplayTagList=(Tag="StateTree",DevComment="")
+GameplayTagList=(Tag="StateTree.Action",DevComment="")
+GameplayTagList=(Tag="StateTree.Action.Attack",DevComment="")
+GameplayTagList=(Tag="StateTree.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion.Idle",DevComment="")
+GameplayTagList=(Tag="StateTree.Locomotion.Movement",DevComment="")
+GameplayTagList=(Tag="StateTree.Status",DevComment="")

